xcodeproj 'xjf/xjf.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'xjf' do
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'ZFPlayer', '~> 1.0.5’
pod 'Masonry', '~> 1.0.0'
pod 'XRCarouselView', '~> 2.4.4'
pod 'RTLabel', '~> 1.0.1'
pod 'libWeChatSDK', '~> 1.6'
pod 'WeiboSDK', '~> 3.1.3'
pod 'TencentOpenApiSDK', '~> 2.9.5'
pod 'JSONModel','~> 1.2.0'

end

# pod can't find: Menu, XMShareView
# can't find, but on github: SCNavTabBar, UzysGridView, YRBackGesture, ZFTabBar
# others can be replaced by pod