xcodeproj 'xjf/xjf.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'xjf' do
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'ZFPlayer', '~> 1.0.5’
pod 'Masonry', '~> 1.0.0'	
end

# pod can't find: Menu, XMShareView
# can't find, but on github: SCNavTabBar, UzysGridView, YRBackGesture, ZFTabBar
# others can be replaced by pod